# Generated by Django 4.1 on 2022-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='about',
            new_name='about1',
        ),
        migrations.AddField(
            model_name='home',
            name='about2',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
