# Generated by Django 4.1 on 2022-08-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_about_home_about1_home_about2'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='image')),
                ('name', models.CharField(max_length=40, verbose_name='Indtroduceing')),
                ('about1', models.TextField(verbose_name='Text')),
                ('about2', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
    ]
