# Generated by Django 4.1 on 2022-08-31 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img',
        ),
    ]
