# Generated by Django 4.1 on 2022-08-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_about_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='About2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Indtroduceing')),
                ('about1', models.TextField(verbose_name='Text')),
                ('about2', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'About2',
                'verbose_name_plural': 'Abouts2',
            },
        ),
    ]
