# Generated by Django 4.1 on 2022-09-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bgimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgimg',
            name='name',
            field=models.CharField(default=1, max_length=40, verbose_name='Indtroduceing'),
            preserve_default=False,
        ),
    ]
