# Generated by Django 4.1 on 2022-09-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bgimg_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bgimg',
        ),
    ]
