# Generated by Django 4.1 on 2022-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_banner_remove_slider_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='about2',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='name',
            new_name='name1',
        ),
        migrations.AddField(
            model_name='slider',
            name='name2',
            field=models.CharField(default=1, max_length=40, verbose_name='Slider_Name'),
            preserve_default=False,
        ),
    ]
