# Generated by Django 4.1 on 2022-09-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_slider_bigimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AddField(
            model_name='slider',
            name='banner',
            field=models.CharField(default=1, max_length=40, verbose_name='Banner_Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='name1',
            field=models.CharField(max_length=40, verbose_name='Slider_Name1'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name2',
            field=models.CharField(max_length=40, verbose_name='Slider_Name2'),
        ),
    ]
