# Generated by Django 4.1 on 2022-09-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_banner_slider_banner_alter_slider_name1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='banner',
        ),
    ]
