# Generated by Django 4.1 on 2022-09-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_clientimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientimg',
            options={'verbose_name': 'Clientimg', 'verbose_name_plural': 'Clientsimgs'},
        ),
    ]
