# Generated by Django 4.1 on 2022-09-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_clientimg_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='img',
        ),
        migrations.RemoveField(
            model_name='client',
            name='link',
        ),
    ]
