# Generated by Django 4.1 on 2022-09-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_client_img_remove_client_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetsTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('about1', models.TextField(verbose_name='Text')),
                ('about2', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'LetsTalk',
                'verbose_name_plural': 'LetsTalks',
            },
        ),
    ]
